name: main

type: php:5.6

web:
    document_root: "/"
    passthru: "/index.php"

hooks:
    # testing out some build stuff
    build: |
      cp LICENSE LICENSE.build
    deploy: |
      cp LICENSE LICENSE.deploy

