
web:
    type: php
    port: 8000
    command: "php -S 0.0.0.0:8000"

hooks:
    # testing out some build stuff
    build: |
      cp LICENSE LICENSE.build
    deploy: |
      cp LICENSE LICENSE.deploy

