
web:
    type: php
    port: 8000
    command: "php -S localhost:8000 -t web"

hooks:
    # testing out some build stuff
    build: |
      cp LICENSE LICENSE.build
    deploy: |
      cp LICENSE LICENSE.deploy

